services:
  alpine:
    image: dev/alpine:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    user: 1000:1000
    volumes:
      - /opt:/opt
      - ${HOME}/projects:/home/dev/projects:z
      - ${HOME}/.config/nvim:/home/dev/.config/nvim:z
